server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/

#    spring.datasource.hikari.auto-commit=false
