server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 123
    url: jdbc:postgresql://localhost:5433/postgres
    hikari:
      auto-commit: false
    tomcat:
      remove-abandoned: true
      remove-abandoned-timeout: 60
  jpa:
    hibernate:
      ddl-auto: update



  thymeleaf:
    prefix: classpath:/templates/


