<!doctype html>
<html lang="en">
<head>
    <title>Home</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/css/mainpage.css">
</head>
<body>
<div class="navigationBox">
    <div class="container">
        <div class="titleBox">
            <h2>BuyCar</h2>
        </div>
        <div class="navContainer">
            <div class="navController">
                <a href="/car/carlist">cars</a>
                <a href="/addcarpage">add</a>
                <a href="">profile</a>
            </div>
            <div class="searchBox">
                <input type="text">
                <button>search</button>
            </div>

        </div>
    </div>
</div>
<div class="maincontainer">

</div>
</body>
</html>