<!doctype html>
<html lang="en">
<head>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="./css/homePage.css">
    <title>Home</title>
</head>
<body>
<div class="navigationBox">
    <div class="container">
        <div class="titleBox">
            <h2>BuyCar.</h2>
        </div>
        <div class="navContainer">
            <div class="navController">
                <a href="/car/carlist">Cars</a>
                <a href="/addcarpage">Add</a>
                <a href="">Profile</a>
            </div>
            <div class="searchBox">
                <input type="text">
                <button><i class='bx bx-search'></i></button>
            </div>

        </div>
    </div>
</div>
</body>
</html>