<!doctype html>
<html lang="en">
<head>
    <title>Home</title>
</head>
<body>
<div class="navigationBox">
    <div class="container">
        <div class="titleBox">
            <h2>BuyCar.</h2>
        </div>
        <div class="navContainer">
            <div class="navController">
                <a href="/car/carlist">Cars</a>
                <a href="/addcarpage">Add</a>
                <a href="">Profile</a>
            </div>
            <div class="searchBox">
                <input type="text">
                <button>search</button>
            </div>

        </div>
    </div>
</div>
</body>
</html>